// @link: https://developer.wordpress.org/themes/advanced-topics/build-process/

// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities.
const path = require('path');

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'js/theme': path.resolve(process.cwd(), 'assets/js', 'theme.js'),
			'css/editor': path.resolve(
				process.cwd(),
				'assets/css',
				'editor.scss'
			),
			'css/theme': path.resolve(
				process.cwd(),
				'assets/css',
				'theme.scss'
			),
		},
		module: {
			rules: [
				// Inherit all default rules.
				...defaultConfig.module.rules,

				// Custom rule for handling font files without a hash in the filename.
				// This is useful when preloading fonts via PHP.
				{
					test: /\.(woff|woff2|eot|ttf|otf)$/i,
					type: 'asset/resource',
					generator: {
						filename: 'fonts/[name][ext]', // Output without hash
					},
				},
			],
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin({
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			}),
		],
	},
};
